name: Generated APK (Upload - Create Artifact To Github Action)

env:
  # The name of the main module repository
  main_project_module: app

  # The name of the Play Store
  playstore_name: Store It

on:
  push:
    branches:
      - 'release/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Set Repository Name As Env Variable
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '21'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      # Run Tests Build
      #- name: Run gradle tests
      #  run: ./gradlew test

      # Run Build Project
      - name: Build gradle project
        run: ./gradlew build --refresh-dependencies

           # Extract Version from Build Script
      - name: Extract version from build.gradle.kts
        id: extract_version
        run: |
          VERSION_MAJOR=$(grep 'val versionMajor' app/build.gradle.kts | head -1 | cut -d'=' -f2 | tr -d ' ' | tr -d '\n')
          VERSION_MINOR=$(grep 'val versionMinor' app/build.gradle.kts | head -1 | cut -d'=' -f2 | tr -d ' ' | tr -d '\n')
          VERSION_PATCH=$(grep 'val versionPatch' app/build.gradle.kts | head -1 | cut -d'=' -f2 | tr -d ' ' | tr -d '\n')
          echo "VERSION_MAJOR=$VERSION_MAJOR" >> $GITHUB_ENV
          echo "VERSION_MINOR=$VERSION_MINOR" >> $GITHUB_ENV
          echo "VERSION_PATCH=$VERSION_PATCH" >> $GITHUB_ENV
          echo "VERSION=$VERSION_MAJOR.$VERSION_MINOR.$VERSION_PATCH" >> $GITHUB_ENV
          echo "Extracted Version: $VERSION_MAJOR.$VERSION_MINOR.$VERSION_PATCH"

      # Create APK Release
      - name: Build apk release project (APK) - ${{ env.main_project_module }} module
        run: ./gradlew assemble

      # Create Bundle AAB Release
      # Noted for main module build [main_project_module]:bundleRelease
      #- name: Build app bundle release (AAB) - ${{ env.main_project_module }} module
      #  run: ./gradlew ${{ env.main_project_module }}:bundleRelease

      # Upload Artifact Build
      # Noted For Output [main_project_module]/build/outputs/apk/release/

      - name: Upload APK Release - ${{ env.repository_name }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - APK release generated
          path: ${{ env.main_project_module }}/build/outputs/apk/release/

      - name: Rename APK
        run: mv ${{ env.main_project_module }}/build/outputs/apk/release/app-release-unsigned.apk ${{ env.main_project_module }}/build/outputs/apk/release/StoreIt-release.apk

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false
      
      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.main_project_module }}/build/outputs/apk/release/StoreIt-release.apk
          asset_name: StoreIt-release.apk
          asset_content_type: application/vnd.android.package-archive

